"""oauth_user

Revision ID: 6997e954c36b
Revises: 0b2b4c10cfd5
Create Date: 2024-05-08 02:01:31.972499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6997e954c36b'
down_revision: Union[str, None] = '0b2b4c10cfd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_oauth_link_to_user', 'oauth_user', ['user_id', 'provider_user_id', 'provider'])
    op.create_unique_constraint(None, 'oauth_user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_user', type_='unique')
    op.drop_constraint('unique_oauth_link_to_user', 'oauth_user', type_='unique')
    # ### end Alembic commands ###
